language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - cp init-db.env.example init-db.env
  - cp src/.env.example src/.env

script:
  - docker-compose up -d
  - docker ps | grep -q easypost-ui
  - docker ps | grep -q easypost-db
  - ./vendor/bin/phpunit
  - ./vendor/bin/phplint ./src --exclude=vendor
