language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - cd laravel

install:
  - composer self-update
  - composer install

before_script:
  - cd ..

script:
  - shellcheck setup.sh
  - docker-compose up -d
  - docker ps | grep -q easypost-ui
  - ./laravel/vendor/bin/phplint ./laravel --exclude=vendor
