language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - cp init-db.env.example init-db.env
  - cd src
  - cp .env.example .env

install:
  - composer self-update
  - composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

script:
  - shellcheck ../setup.sh
  - docker-compose up -d
  - docker ps | grep -q easypost-ui
  - ./vendor/bin/phpunit
  - ./vendor/bin/phplint ./src --exclude=vendor
