language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4

before_install: cd laravel
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

install: 
  - docker build -t easypost-ui .
  - docker run -d -p 127.0.0.1:8000:80 --name easypost-ui easypost-ui

script: 
-  docker ps | grep -q easypost-ui
