language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - cd src

install:
  - composer self-update
  - composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

before_script:
  - cd ..

script:
  - shellcheck setup.sh
  - docker-compose up -d
  - docker ps | grep -q easypost-ui
  - ./src/vendor/bin/phplint ./src --exclude=vendor
