language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - cd laravel

install:
  - composer self-update
  - composer install

before_script:
  - cd ..

script:
  - docker build -t easypost-ui .
  - docker run -d -p 127.0.0.1:8000:80 --name easypost-ui easypost-ui
  - docker ps | grep -q easypost-ui
