version: "3.8"
services:
  easypost-tools-ui:
    deploy:
      replicas: 2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - traefik.frontend.rule=Host:easyposttools.com,www.easyposttools.com
    volumes:
      - ./src/storage/logs:/var/www/html/storage/logs
      - ./src/storage/app/public:/var/www/html/storage/app/public
  # The `easypost-tools-db` and `easypost-tools-db-replica` containers will automatically restart on a failure, no custom healthcheck needed
