version: "3.7"
services:

    easypost-ui:
        build: .
        restart: always
        container_name: easypost-ui
        volumes: 
            - ./src/storage:/var/www/html/storage
        networks:
            - easypost-ui
            - traefik
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:easypost.localhost
            - traefik.port=80

    easypost-db:
        image: mysql:8.0.18
        restart: always
        container_name: easypost-db
        env_file:
            - init-db.env
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - easypost-ui
        labels:
            - traefik.enable=false

networks:
    easypost-ui:
        name: easypost-ui
    traefik:
        external:
            name: traefik
