version: "3.7"
services:

    nginx:
        image: nginx:latest
        restart: always
        container_name: easypost-ui-nginx
        volumes:
            - ./laravel:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            - easypost-ui

    php:
        build: .
        restart: always
        container_name: easypost-ui-php
        volumes:
            - ./laravel:/var/www/html
        networks:
            - easypost-ui

networks:
    easypost-ui:
        name: easypost-ui
