version: "3.7"
services:

    easypost-ui:
        build: .
        restart: always
        container_name: easypost-ui
        volumes: 
            - ./src:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            - easypost-ui

    easypost-db:
        image: mysql:8
        restart: always
        container_name: easypost-db
        env_file:
            - init-db.env
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - easypost-ui
        ports:
            - "3306:3306"

networks:
    easypost-ui:
        name: easypost-ui
