version: "3.8"
services:
  easypost-tools-ui:
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.http.routers.easyposttools.rule=Host(`easyposttools.com`) || Host(`www.easyposttools.com`)"
      - "traefik.http.routers.easyposttools.tls=true"
      - "traefik.http.routers.easyposttools.tls.certresolver=letsencrypt"
    volumes:
      - ./src/storage/logs:/var/www/html/storage/logs
      - ./src/storage/app/public:/var/www/html/storage/app/public
  easypost-tools-db:
      healthcheck:
        test: ["CMD", "mysql", "-u${MARIADB_USER}", "-p${MARIADB_PASSWORD}", "-e", "show databases;"]
        interval: 30s
        timeout: 10s
        retries: 3
