version: "3.7"
services:

    easypost-ui:
        build: .
        restart: always
        container_name: easypost-ui
        ports:
            - "8000:80"
        networks:
            - easypost-ui

networks:
    easypost-ui:
        name: easypost-ui
