services:
  easypost-tools-ui:
    build: .
    restart: always
    env_file:
      - src/.env
    networks:
      - easypost-tools-ui
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.port=80
  easypost-tools-db:
    image: 'bitnami/mariadb:10.6.5'
    restart: always
    volumes:
      - database-data:/bitnami/mariadb
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_SKIP_TEST_DB=yes
    env_file:
      - database.env
    networks:
      - easypost-tools-ui
    labels:
      - traefik.enable=false
  easypost-tools-db-replica:
    image: 'bitnami/mariadb:10.6.5'
    restart: always
    depends_on:
      - easypost-tools-db
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_MASTER_HOST=easypost-tools-db
    env_file:
      - database.env
    networks:
      - easypost-tools-ui
    labels:
      - traefik.enable=false

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
  easypost-tools-ui:
    name: easypost-tools-ui
