version: "3.7"
services:

    easypost-ui:
        build: .
        restart: always
        container_name: easypost-ui
        volumes: 
            - ./src/storage/logs:/var/www/html/storage/logs
            - ./src/storage/app/public:/var/www/html/storage/app/public
            - ./src/.env:/var/www/html/.env
        ports:
            - "8000:80"
        networks:
            - easypost-ui

    easypost-db:
        image: mysql:8
        restart: always
        container_name: easypost-db
        env_file:
            - init-db.env
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - easypost-ui

networks:
    easypost-ui:
        name: easypost-ui
