services:
  easypost-tools-ui:
    build:
      args:
        PROD: true
    deploy:
      replicas: 2
    mem_limit: '512m'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      start_period: 10s
      start_interval: 1s
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.http.routers.easyposttools.rule=Host(`easyposttools.com`, `www.easyposttools.com`)'
      - 'traefik.http.routers.easyposttools.tls=true'
      - 'traefik.http.routers.easyposttools.tls.certresolver=letsencrypt'
    volumes:
      - ./src/storage/logs:/var/www/html/storage/logs
      - ./src/storage/app/public:/var/www/html/storage/app/public
  easypost-tools-ui-db:
    mem_limit: '768m'
    healthcheck:
      test: ['CMD', 'mariadb', '-u${MARIADB_USER}', '-p${MARIADB_PASSWORD}', '-e', 'show databases;']
      start_period: 10s
      start_interval: 1s
      interval: 30s
      timeout: 10s
      retries: 3
