services:
  easypost-tools-ui:
    build: .
    restart: always
    env_file:
      - src/.env
    networks:
      - easypost-tools-ui
      - traefik
    labels:
      - traefik.enable=true
    depends_on:
       - easypost-tools-db
  easypost-tools-db:
    image: 'mariadb:10.10.3'
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - easypost-tools-ui

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
    external: true
  easypost-tools-ui:
    name: easypost-tools-ui
