services:
  easypost-tools-ui:
    build: .
    restart: always
    networks:
      - easypost-tools-ui
      - traefik
    env_file:
      - src/.env
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.easypost-tools-ui.rule=Host(`easyposttools.localhost`)'
      - 'traefik.http.services.easypost-tools-ui.loadbalancer.server.port=80'
    depends_on:
      easypost-tools-ui-db:
        condition: service_started
    volumes:
      - ./src:/var/www/html

  easypost-tools-ui-db:
    image: 'mariadb:11.4.7'
    restart: always
    volumes:
      - easypost-tools-ui-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: easypost_tools
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: easypost_tools
      MARIADB_PASSWORD: password
      MARIADB_AUTO_UPGRADE: 1
    networks:
      - easypost-tools-ui

volumes:
  easypost-tools-ui-data:
    driver: local

networks:
  traefik:
    external: true
  easypost-tools-ui:
    name: easypost-tools-ui
