services:
  easypost-tools-ui:
    build: .
    # image: justintime50/easypost-tools-ui
    restart: always
    env_file:
      - src/.env
    networks:
      - easypost-tools-ui
      - traefik
  easypost-tools-ui-db:
    image: 'mariadb:11.4.3'
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - easypost-tools-ui

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
    external: true
  easypost-tools-ui:
    name: easypost-tools-ui
