services:
  easypost-tools-ui:
    build: .
    restart: unless-stopped
    env_file:
      - src/.env
    networks:
      - easypost-tools-ui
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.port=80

networks:
  traefik:
    name: traefik
  easypost-tools-ui:
    name: easypost-tools-ui
