version: "3.7"
services:

    easypost-ui:
        build: .
        restart: always
        container_name: easypost-ui
        volumes: 
            - ./src/storage:/var/www/html/storage
            - ./src/.env:/var/www/html/.env # to avoid needing to recreate the key every build
        ports:
            - "8000:80"
        networks:
            - easypost-ui

    easypost-db:
        image: mysql:8.0.18
        restart: always
        container_name: easypost-db
        env_file:
            - init-db.env
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - easypost-ui

networks:
    easypost-ui:
        name: easypost-ui
