name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.1', '8.2', '8.3']
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Sign into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image and push to Docker Hub
        run: docker buildx build --push -t justintime50/easypost-tools-ui:${GITHUB_REF##*/} --build-arg PROD=true --platform linux/amd64,linux/arm64 .
